# Generated by Django 4.2.1 on 2023-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enquiry_homechoose'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('textarea', models.TextField()),
            ],
            options={
                'db_table': 'home_enquiry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeHomechoose',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('where', models.CharField(max_length=100)),
                ('when', models.DateField()),
            ],
            options={
                'db_table': 'home_homechoose',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='enquiry',
        ),
        migrations.DeleteModel(
            name='homechoose',
        ),
    ]
